"""580 · Novae — graph-based foundation model for spatial transcriptomics (spatial domains / niches).

本模块做两件事:
  1) **可跑基线(默认,纯本机依赖)**: 用两个朴素的空间域划分器做跨切片 niche 分割 ——
     (a) expression-only  : PCA + KMeans, 完全不用空间信息(空间信息的"地板");
     (b) niche-smoothing  : 先在空间 kNN 邻域内做表达平滑(经典 niche 构造), 再 PCA + KMeans。
     两者都用 **Novae 论文自己的评价指标** 打分(FIDE / JSD / heuristic, 见下), 因此
     Novae 的任何"更好"都必须相对这条地板来读, 而不是单独报告。
  2) **Novae 守卫式封装(--run-novae)**: 上游包未安装 / 基因名不是真实 human-mouse symbol /
     无法访问 HuggingFace 权重时, 优雅退出并打印真实安装与调用命令, 绝不假装跑过。

评价指标按上游源码复刻(非臆造), 逐行对照 novae/monitor/eval.py(v1.1.1):
    - fide_score               (eval.py:34)  F1-score of intra-domain edges, 越高域越连续
    - jensen_shannon_divergence(eval.py:65 / _jensen_shannon_divergence eval.py:95)
    - entropy                  (eval.py:112) EPS 取上游 Nums.EPS = 1e-8 (_constants.py:47)
    - heuristic                (eval.py:143 / _heuristic eval.py:162) 逐切片算再平均
唯一改动: 上游从 adata.obsp["spatial_distances"] 取邻接, 本模块换成显式 kNN 边表。
另加 ARI(对合成数据的 ground-truth domain), 作为独立 sanity-check。

Novae API(全部在本地上游源码中核对过定义位置):
    novae.spatial_neighbors(adata, *, slide_key=None, ...)   novae/utils/build.py:35
    novae.Novae.from_pretrained(model_name_or_path)          novae/model.py:309
    model.compute_representations(adata, *, zero_shot=False) novae/model.py:379
    model.assign_domains(adata, level=7, n_domains=None)->str novae/model.py:539

Blampey Q, et al. Novae: a graph-based foundation model for spatial transcriptomics data.
Nat Methods. 2025;22(12):2539-2550. doi:10.1038/s41592-025-02899-6 · PMID 41372623
Repo https://github.com/prism-oncology/novae (旧地址 MICS-Lab/novae 会 302 到此)
Docs https://prism-oncology.github.io/novae/
"""
from __future__ import annotations

import argparse
import json
import os
import sys
import warnings
from pathlib import Path

warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parent
MODULES = ROOT.parents[2]                       # .../modules
sys.path.insert(0, str(MODULES / "_framework"))
from pubstyle import (CMAP_CONT, NATURE_W1, NATURE_W2, pal, save_fig,  # noqa: E402
                      set_pub_style)

import matplotlib.pyplot as plt  # noqa: E402

EXAMPLE = ROOT / "example_data" / "spatial_demo_cells.csv"
SEED = 0


# ---------------------------------------------------------------------------
# 合成示例数据: 3 张切片, 共享同一套真实空间域, 但各自带切片特异的批次漂移。
#
# ★ 关键设计(否则这个 demo 就不是 niche 问题): **域不是由单细胞表达定义的**, 而是由
#   邻域内的细胞类型**组成比例**定义的 —— 4 种细胞类型在所有域中都出现, 只是比例不同。
#   因此单看一个细胞的表达只能还原它的细胞类型, 还原不了它属于哪个空间域; 必须看邻域。
#   这正是 Novae 这类 niche 基础模型要解决的问题, 也让 expression-only 成为真实的地板。
# ---------------------------------------------------------------------------
def make_example(path: Path, n_slides: int = 3, per_side: int = 18,
                 n_genes: int = 40, seed: int = SEED) -> pd.DataFrame:
    rng = np.random.default_rng(seed)
    n_dom, n_ct = 4, 4
    # 细胞类型 -> 基因程序(表达只由细胞类型决定)
    programs = rng.gamma(2.0, 1.0, size=(n_ct, n_genes))
    # 域 -> 细胞类型组成: 主导型占 55%, 其余各 15%
    comp = np.full((n_dom, n_ct), 0.15)
    comp[np.arange(n_dom), np.arange(n_ct)] = 0.55
    comp = comp / comp.sum(1, keepdims=True)
    rows = []
    for s in range(n_slides):
        gx, gy = np.meshgrid(np.arange(per_side), np.arange(per_side))
        x = gx.ravel() + rng.normal(0, 0.18, gx.size)      # 抖动, 避免完美格点
        y = gy.ravel() + rng.normal(0, 0.18, gy.size)
        # 真实域: 左右条带 x 上下条带 -> 4 个空间连续的区块
        dom = (gx.ravel() >= per_side / 2).astype(int) * 2 + (gy.ravel() >= per_side / 2).astype(int)
        # 细胞类型按所在域的组成比例抽样(域内混杂, 这是 niche 的本质)
        ct = np.array([rng.choice(n_ct, p=comp[d]) for d in dom])
        mu = programs[ct]
        batch = rng.lognormal(0.0, 0.35, size=(1, n_genes))   # 切片特异乘性批次效应
        counts = rng.poisson(np.clip(mu * batch, 0.05, None))
        df = pd.DataFrame(counts, columns=[f"G{i:03d}" for i in range(n_genes)])
        df.insert(0, "cell_type_true", [f"CT{c}" for c in ct])
        df.insert(0, "domain_true", [f"D{d}" for d in dom])
        df.insert(0, "y", np.round(y, 3))
        df.insert(0, "x", np.round(x, 3))
        df.insert(0, "slide", f"slide{s + 1}")
        df.insert(0, "cell_id", [f"s{s + 1}_c{i:04d}" for i in range(len(df))])
        rows.append(df)
    out = pd.concat(rows, ignore_index=True)
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", newline="", encoding="utf-8") as fh:
        fh.write("# synthetic, for demo only -- generated by 580_novae_spatial_fm.py\n")
        out.to_csv(fh, index=False)
    return out


def load_table(path: Path) -> pd.DataFrame:
    return pd.read_csv(path, comment="#")


# ---------------------------------------------------------------------------
# 指标: 复刻自 novae/monitor/eval.py (URL 见文件头), 只把 adata.obsp 换成显式邻接
# ---------------------------------------------------------------------------
def _entropy(p: np.ndarray) -> float:
    """Shannon entropy(上游 entropy(), EPS 与上游 Nums.EPS 同量级)。"""
    return float(-(p * np.log2(p + 1e-8)).sum())


def fide_score(labels: np.ndarray, edges: tuple[np.ndarray, np.ndarray],
               n_classes: int | None = None) -> float:
    """F1-score of intra-domain edges(FIDE): 边两端标签当作 y_true/y_pred 求逐类 F1 后平均。"""
    from sklearn.metrics import f1_score
    i, j = edges
    f1 = f1_score(labels[i], labels[j], average=None)
    if n_classes is None:
        return float(f1.mean())
    return float(np.pad(f1, (0, max(0, n_classes - len(f1)))).mean())


def mean_fide(labels: np.ndarray, edges_by_slide: dict, slide: np.ndarray,
              n_classes: int) -> float:
    vals = []
    for sid, (i, j) in edges_by_slide.items():
        m = slide == sid
        idx = np.where(m)[0]
        remap = {g: k for k, g in enumerate(idx)}
        vals.append(fide_score(labels[m], (np.array([remap[k] for k in idx[i]]),
                                           np.array([remap[k] for k in idx[j]])),
                               n_classes=n_classes))
    return float(np.mean(vals))


def jensen_shannon_divergence(labels: np.ndarray, slide: np.ndarray) -> float:
    """跨切片域分布 JSD。越低 = 域在切片间越一致(可迁移), 上游 _jensen_shannon_divergence。"""
    cats = sorted(set(labels))
    dists = []
    for sid in sorted(set(slide)):
        v = pd.Series(labels[slide == sid]).value_counts()
        dists.append(np.array([v.get(c, 0) for c in cats], dtype=float))
    D = np.array(dists)
    D = D / D.sum(1)[:, None]
    return float(_entropy(D.mean(0)) - np.mean([_entropy(d) for d in D]))


def heuristic(labels: np.ndarray, edges_by_slide: dict, slide: np.ndarray,
              n_classes: int) -> float:
    """上游 heuristic(): 对每张切片各算 fide * entropy(该片域占比) / log2(n_classes), 再跨片平均。

    严格对齐 novae/monitor/eval.py 的 heuristic()/_heuristic() —— 上游是**逐切片**算完整式子
    再取均值(mean over _heuristic per slide), 不是"平均 FIDE × 全局 entropy"。
    """
    vals = []
    for sid, (i, j) in edges_by_slide.items():
        m = slide == sid
        idx = np.where(m)[0]
        remap = {g: k for k, g in enumerate(idx)}
        fide_s = fide_score(labels[m], (np.array([remap[k] for k in idx[i]]),
                                        np.array([remap[k] for k in idx[j]])),
                            n_classes=n_classes)
        p = pd.Series(labels[m]).value_counts(normalize=True).values
        p = np.pad(p, (0, max(0, n_classes - len(p))))
        vals.append(fide_s * _entropy(p) / np.log2(n_classes))
    return float(np.mean(vals))


# ---------------------------------------------------------------------------
# 基线方法
# ---------------------------------------------------------------------------
def _spatial_edges(xy: np.ndarray, k: int = 6):
    """切片内空间 kNN 图, 返回对称化的 (i, j) 边列表。"""
    from sklearn.neighbors import kneighbors_graph
    A = kneighbors_graph(xy, n_neighbors=min(k, len(xy) - 1), mode="connectivity")
    A = ((A + A.T) > 0).astype(int)
    return A.nonzero()


def _normalize_log(X: np.ndarray) -> np.ndarray:
    """CPM-style 归一 + log1p(scanpy 默认前处理的等价最小实现)。"""
    tot = X.sum(1, keepdims=True)
    tot[tot == 0] = 1.0
    return np.log1p(X / tot * np.median(tot))


def baseline_expression_only(X: np.ndarray, n_domains: int, seed: int = SEED) -> np.ndarray:
    """地板 A: 完全忽略空间坐标, PCA + KMeans。空间模型若打不过它, 空间信息就没用上。"""
    from sklearn.cluster import KMeans
    from sklearn.decomposition import PCA
    Z = PCA(n_components=min(20, X.shape[1] - 1), random_state=seed).fit_transform(X)
    lab = KMeans(n_clusters=n_domains, n_init=20, random_state=seed).fit_predict(Z)
    return np.array([f"E{c}" for c in lab])


def baseline_niche_smoothing(X: np.ndarray, xy: np.ndarray, slide: np.ndarray,
                             n_domains: int, k: int = 20, seed: int = SEED,
                             center_per_slide: bool = False, prefix: str = "N") -> np.ndarray:
    """地板 B: 空间 kNN 邻域内平均表达(经典 niche 构造) -> PCA + KMeans。

    这是空间域划分最朴素但很难打败的对照 —— 任何 niche 基础模型的增益都应相对它衡量。

    center_per_slide=True 时先做**逐切片 z-score**, 这是最朴素的批次处理(Harmony 的
    穷人版)。不加这一步时, 邻域平均会把细胞类型噪声抹掉、反而让切片批次成为主方差方向,
    KMeans 就会按切片而不是按域聚类 —— 本模块默认把两个变体都跑出来, 让这件事看得见。
    """
    from sklearn.cluster import KMeans
    from sklearn.decomposition import PCA
    from sklearn.neighbors import kneighbors_graph
    S = np.zeros_like(X)
    for sid in np.unique(slide):
        m = slide == sid
        A = kneighbors_graph(xy[m], n_neighbors=min(k, m.sum() - 1), mode="connectivity")
        A = A + np.eye(m.sum())          # 含自身
        S[m] = np.asarray(A @ X[m]) / np.asarray(A.sum(1))
        if center_per_slide:             # 逐切片 z-score, 消掉切片特异的均值/尺度漂移
            sd = S[m].std(0); sd[sd == 0] = 1.0
            S[m] = (S[m] - S[m].mean(0)) / sd
    Z = PCA(n_components=min(20, X.shape[1] - 1), random_state=seed).fit_transform(S)
    lab = KMeans(n_clusters=n_domains, n_init=20, random_state=seed).fit_predict(Z)
    return np.array([f"{prefix}{c}" for c in lab])


# ---------------------------------------------------------------------------
# Novae 守卫式路径
# ---------------------------------------------------------------------------
def run_novae(df: pd.DataFrame, gene_cols: list[str], slide_key: str,
              n_domains: int, model_name: str, level: int) -> dict:
    """真正跑 Novae。任一前置条件不满足 -> 返回 skipped + 真实的补救命令, 不伪造结果。

    调用序列已逐个在上游源码里核对(文件:行见模块 docstring):
        novae.spatial_neighbors(adata, slide_key=...)          utils/build.py:35
        novae.Novae.from_pretrained("prism-oncology/novae-human-0")  model.py:309
        model.compute_representations(adata, zero_shot=True)   model.py:379
        model.assign_domains(adata, level=..., n_domains=...)  model.py:539
    注: 上游 assign_domains 在 zero-shot 下会 log.warning 建议改用 resolution=(见
    model.py:588); 本封装保留 level/n_domains 路径, 需要时用 --novae-level 调。
    """
    try:
        import novae
    except ImportError as e:
        return {"status": "skipped",
                "reason": f"novae 未安装 ({e.name}); 需要 Python>=3.11 与 torch-geometric",
                "install": "pip install novae"}
    try:
        import anndata as ad
        A = ad.AnnData(df[gene_cols].to_numpy(dtype="float32"))
        A.var_names = gene_cols
        A.obs_names = df["cell_id"].astype(str).values
        A.obs[slide_key] = pd.Categorical(df[slide_key].values)
        A.obsm["spatial"] = df[["x", "y"]].to_numpy(dtype="float32")

        novae.spatial_neighbors(A, slide_key=slide_key)
        model = novae.Novae.from_pretrained(model_name)
        model.compute_representations(A, zero_shot=True)
        key = model.assign_domains(A, level=level, n_domains=n_domains)
        return {"status": "ok", "novae_version": getattr(novae, "__version__", "?"),
                "domain_key": key, "labels": A.obs[key].astype(str).tolist()}
    except Exception as e:                     # 权重下载失败 / 基因名非真实 symbol 等
        return {"status": "failed",
                "reason": f"{type(e).__name__}: {e}",
                "note": ("Novae 依赖真实 human/mouse 基因 symbol 做基因嵌入, 合成数据的 G000 "
                         "这类占位名不可用; 且 from_pretrained 需能访问 HuggingFace Hub。"
                         "请传 --csv 你的真实数据, 并确认网络可达。")}


# ---------------------------------------------------------------------------
# 出图(全部非条形图: 空间散点 / 棒棒糖 / 热图)
# ---------------------------------------------------------------------------
def fig_domain_maps(df: pd.DataFrame, methods: dict, outstem: Path) -> None:
    """空间散点: 行=方法(含 ground truth), 列=切片。看域是否空间连续、跨切片是否对齐。"""
    slides = sorted(df["slide"].unique())
    names = ["Ground truth"] + list(methods)
    labsets = [df["domain_true"].values] + [methods[m] for m in methods]
    fig, axes = plt.subplots(len(names), len(slides),
                             figsize=(NATURE_W2, 2.0 * len(names)), squeeze=False)
    for r, (nm, lab) in enumerate(zip(names, labsets)):
        cats = sorted(set(lab))
        cmap = dict(zip(cats, pal(len(cats), "okabe_ito")))
        for c, sid in enumerate(slides):
            ax = axes[r][c]
            m = df["slide"].values == sid
            ax.scatter(df["x"].values[m], df["y"].values[m],
                       c=[cmap[v] for v in np.asarray(lab)[m]], s=6, linewidths=0)
            ax.set_xticks([]); ax.set_yticks([]); ax.set_aspect("equal")
            for sp in ax.spines.values():
                sp.set_visible(True)
            if r == 0:
                ax.set_title(sid, fontsize=9)
            if c == 0:
                ax.set_ylabel(nm, fontsize=8)
    fig.suptitle("Spatial domain assignment across slides", fontsize=11, fontweight="bold")
    fig.tight_layout()
    save_fig(fig, outstem)
    plt.close(fig)


def fig_metric_lollipop(metrics: pd.DataFrame, outstem: Path) -> None:
    """棒棒糖图比较各方法的 FIDE / heuristic / ARI(越高越好)与 JSD(越低越好)。"""
    panels = [("FIDE", "higher = more continuous domains", False),
              ("heuristic", "higher = continuous + balanced", False),
              ("ARI", "higher = closer to ground truth", False),
              ("JSD", "lower = shared across slides", True)]
    fig, axes = plt.subplots(1, len(panels), figsize=(NATURE_W2, 2.6), sharey=True)
    colors = pal(len(metrics), "npg")
    ypos = np.arange(len(metrics))[::-1]
    for ax, (col, sub, lower_better) in zip(axes, panels):
        v = metrics[col].values
        ax.hlines(ypos, 0, v, color="#BBBBBB", linewidth=1.6, zorder=1)
        ax.scatter(v, ypos, s=70, c=colors, zorder=2, edgecolors="white", linewidths=0.8)
        ax.set_title(col + ("  (lower better)" if lower_better else "  (higher better)"),
                     fontsize=8)
        ax.set_xlabel(sub, fontsize=6)
        ax.set_xlim(0, max(float(np.max(v)) * 1.25, 1e-3))
    axes[0].set_yticks(ypos)
    axes[0].set_yticklabels(metrics["method"].tolist(), fontsize=8)
    fig.suptitle("Baseline spatial-domain callers scored with the Novae metrics",
                 fontsize=10, fontweight="bold")
    fig.tight_layout()
    save_fig(fig, outstem)
    plt.close(fig)


def fig_composition_heatmap(df: pd.DataFrame, methods: dict, outstem: Path) -> None:
    """热图: 每方法下 域 x 切片 的细胞占比。列间越一致 = 域越可跨切片迁移(JSD 的可视化)。"""
    slides = sorted(df["slide"].unique())
    fig, axes = plt.subplots(1, len(methods), figsize=(NATURE_W2, 2.8), squeeze=False)
    for ax, (nm, lab) in zip(axes[0], methods.items()):
        cats = sorted(set(lab))
        M = np.zeros((len(cats), len(slides)))
        for c, sid in enumerate(slides):
            v = pd.Series(np.asarray(lab)[df["slide"].values == sid]).value_counts(normalize=True)
            M[:, c] = [v.get(k, 0.0) for k in cats]
        im = ax.imshow(M, cmap=CMAP_CONT, aspect="auto", vmin=0, vmax=max(0.6, M.max()))
        ax.set_xticks(range(len(slides))); ax.set_xticklabels(slides, fontsize=7, rotation=45)
        ax.set_yticks(range(len(cats))); ax.set_yticklabels(cats, fontsize=7)
        ax.set_title(nm, fontsize=8)
        for sp in ax.spines.values():
            sp.set_visible(False)
    fig.colorbar(im, ax=axes[0].tolist(), shrink=0.8, label="fraction of cells")
    fig.suptitle("Domain composition per slide (column-wise consistency = transferability)",
                 fontsize=10, fontweight="bold", y=1.08)
    save_fig(fig, outstem)
    plt.close(fig)


# ---------------------------------------------------------------------------
def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--csv", default=str(EXAMPLE),
                    help="细胞表: cell_id,slide,x,y[,domain_true],<基因列...>")
    ap.add_argument("--slide-key", default="slide")
    ap.add_argument("--n-domains", type=int, default=4)
    ap.add_argument("--k-niche", type=int, default=20, help="niche 平滑用的空间近邻数")
    ap.add_argument("--k-graph", type=int, default=6, help="FIDE 邻接图的近邻数")
    ap.add_argument("--run-novae", action="store_true", help="尝试真正调用 Novae(需安装 + 真实基因名)")
    ap.add_argument("--novae-model", default="prism-oncology/novae-human-0")
    ap.add_argument("--novae-level", type=int, default=7)
    ap.add_argument("--outdir", default=str(ROOT / "results"))
    ap.add_argument("--assets", default=str(ROOT / "assets"))
    ap.add_argument("--seed", type=int, default=SEED)
    a = ap.parse_args()

    outdir, assets = Path(a.outdir), Path(a.assets)
    outdir.mkdir(parents=True, exist_ok=True); assets.mkdir(parents=True, exist_ok=True)
    np.random.seed(a.seed)
    set_pub_style(base_size=9)

    csv = Path(a.csv)
    if csv == EXAMPLE and not csv.exists():
        print(f"[580] 示例数据不存在, 生成 -> {csv}")
        make_example(csv, seed=a.seed)
    print(f"[580] Step 1 读入 {csv}")
    df = load_table(csv)
    META_COLS = ("cell_id", a.slide_key, "x", "y", "domain_true", "cell_type_true")
    meta = [c for c in META_COLS if c in df.columns]
    gene_cols = [c for c in df.columns if c not in meta]
    slide = df[a.slide_key].astype(str).values
    xy = df[["x", "y"]].to_numpy(float)
    X = _normalize_log(df[gene_cols].to_numpy(float))
    print(f"       {len(df)} cells · {len(gene_cols)} genes · {len(set(slide))} slides")

    print("[580] Step 2 构建切片内空间 kNN 图(FIDE 用)")
    edges_by_slide = {}
    for sid in sorted(set(slide)):
        m = slide == sid
        i, j = _spatial_edges(xy[m], k=a.k_graph)
        edges_by_slide[sid] = (i, j)

    print("[580] Step 3 基线: expression-only / niche-smoothing")
    methods: dict[str, np.ndarray] = {
        "Expression-only (PCA+KMeans)": baseline_expression_only(X, a.n_domains, a.seed),
        "Niche smoothing (kNN)": baseline_niche_smoothing(
            X, xy, slide, a.n_domains, k=a.k_niche, seed=a.seed, prefix="N"),
        "Niche smoothing + per-slide z": baseline_niche_smoothing(
            X, xy, slide, a.n_domains, k=a.k_niche, seed=a.seed,
            center_per_slide=True, prefix="Z"),
    }

    if a.run_novae:
        print("[580] Step 3b Novae(守卫式)")
        r = run_novae(df, gene_cols, a.slide_key, a.n_domains, a.novae_model, a.novae_level)
        for k, v in r.items():
            if k != "labels":
                print(f"       {k}: {v}")
        if r.get("status") == "ok":
            methods["Novae (zero-shot)"] = np.array(r["labels"])
        with open(outdir / "580_novae_status.json", "w", encoding="utf-8") as fh:
            json.dump({k: v for k, v in r.items() if k != "labels"}, fh, indent=1, ensure_ascii=False)
    else:
        print("[580] Novae 路径未请求(--run-novae), 仅跑基线")

    print("[580] Step 4 打分(FIDE / JSD / heuristic / ARI, 指标复刻自上游 monitor/eval.py)")
    from sklearn.metrics import adjusted_rand_score
    rows = []
    for nm, lab in methods.items():
        nc = len(set(lab))
        rows.append({
            "method": nm,
            "n_domains": nc,
            "FIDE": round(mean_fide(lab, edges_by_slide, slide, a.n_domains), 4),
            "JSD": round(jensen_shannon_divergence(lab, slide), 4),
            "heuristic": round(heuristic(lab, edges_by_slide, slide, a.n_domains), 4),
            "ARI": round(adjusted_rand_score(df["domain_true"].values, lab), 4)
            if "domain_true" in df.columns else np.nan,
            # 诊断列: 若某方法 ARI_celltype 高而 ARI(域) 低, 说明它只还原了细胞类型、
            # 根本没抓到 niche —— expression-only 地板正应如此。
            "ARI_celltype": round(adjusted_rand_score(df["cell_type_true"].values, lab), 4)
            if "cell_type_true" in df.columns else np.nan,
        })
    metrics = pd.DataFrame(rows)
    print(metrics.to_string(index=False))
    metrics.to_csv(outdir / "580_metrics.csv", index=False)
    lab_out = df[meta].copy()
    for nm, lab in methods.items():
        lab_out[nm] = lab
    lab_out.to_csv(outdir / "580_domain_labels.csv", index=False)

    print("[580] Step 5 出图")
    fig_domain_maps(df, methods, assets / "580_domain_maps")
    fig_metric_lollipop(metrics, assets / "580_metric_comparison")
    fig_composition_heatmap(df, methods, assets / "580_slide_composition")

    with open(outdir / "580_summary.json", "w", encoding="utf-8") as fh:
        json.dump({"input": str(csv), "n_cells": len(df), "n_genes": len(gene_cols),
                   "slides": sorted(set(slide)), "metrics": rows,
                   "novae_attempted": bool(a.run_novae), "seed": a.seed},
                  fh, indent=1, ensure_ascii=False)
    print(f"[580] 完成 · results -> {outdir} · figures -> {assets}")


if __name__ == "__main__":
    main()
