# -*- coding: utf-8 -*-
"""578 · SpatialEx / SpatialEx+ —— 组织学锚定的空间组学跨模态翻译.

上游方法 SpatialEx 用 H&E 切片图像作为"锚",把一张切片上测到的组学 panel 翻译到
另一张只有 H&E 的切片上;SpatialEx+ 进一步做 panel/omics 对角整合(slice1 测 panel A、
slice2 测 panel B → 两张切片都拿到 A+B)。

本模块提供:
  (1) **本机可跑的朴素基线**(sklearn Ridge):H&E embedding → 基因 panel 的线性回归,
      外加"空间 kNN 平滑"变体(近似上游的超图邻域聚合),并与"全局均值"地板对照。
      这条路径无需装任何包即可跑完出图,是模块的最低可用性底线。
  (2) **守卫式上游封装**:检测 SpatialEx 是否安装 + 是否有 GPU,给出经核实的真实调用序列。

诚实声明:基线是线性回归,**不是** SpatialEx 的 HGNN 复现。它的作用是给上游方法一个
必须被超过的地板——任何"翻译效果好"的说法都要先跟它比。

论文:Liu Y, Wang C, Wang Z, ..., Guan R, Yuan Z.
      High-parameter spatial multi-omics through histology-anchored integration.
      Nature Methods 2026 Feb;23(2):373-386. doi:10.1038/s41592-025-02926-6 · PMID 41407925
      (刊期/卷页经 NCBI efetch 核实;上游 BibTeX 的 year=2025 对应 Epub 2025-12-17)
仓库:https://github.com/KEAML-JLU/SpatialEx
教程:https://spatialex-tutorials.readthedocs.io
"""
from __future__ import annotations

import argparse
import json
import os
import sys
import warnings

warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd

HERE = os.path.dirname(os.path.abspath(__file__))
EXAMPLE = os.path.join(HERE, "example_data")
RESULTS = os.path.join(HERE, "results")
ASSETS = os.path.join(HERE, "assets")

# 框架统一出图样式(modules/_framework/pubstyle.py)
sys.path.insert(0, os.path.abspath(os.path.join(HERE, "..", "..", "..", "_framework")))
from pubstyle import (  # noqa: E402
    CMAP_CONT, CMAP_DIVERGE, NATURE_W1, NATURE_W2, pal, save_fig, set_pub_style,
)

SEED = 0
HEADER = "# synthetic, for demo only -- generated by 578_spatialex_omics_translation.py\n"


# ---------------------------------------------------------------------------
# 1. 合成示例数据:两张连续切片,共享组织程序,各测一个 panel
# ---------------------------------------------------------------------------
def _gaussian_field(coords, n_prog, rng, n_bumps=12, width=220.0):
    """用随机高斯基函数叠加出空间平滑的潜在组织程序活性 (n_cells x n_prog)。

    这样合成的表达谱有真实的空间结构(域/梯度),而不是纯噪声;
    H&E 与组学共享同一批潜在程序 —— 这正是"组织学锚定"能成立的前提。
    """
    n = coords.shape[0]
    z = np.zeros((n, n_prog))
    lo, hi = coords.min(0), coords.max(0)
    for p in range(n_prog):
        for _ in range(n_bumps):
            c = rng.uniform(lo, hi)
            amp = rng.normal(0, 1)
            d2 = ((coords - c) ** 2).sum(1)
            z[:, p] += amp * np.exp(-d2 / (2 * width ** 2))
    return (z - z.mean(0)) / (z.std(0) + 1e-8)


def _make_slice(n_cells, W_he, W_a, W_b, gain_a, gain_b, rng, field_size=1500.0):
    """生成一张切片:空间坐标 + H&E embedding + panel A + panel B(B 部分留作真值)。"""
    n_prog = W_he.shape[0]
    coords = rng.uniform(0, field_size, size=(n_cells, 2))
    z = _gaussian_field(coords, n_prog, rng)

    # H&E embedding:形态学表征 = 潜在程序的投影 + 相当量的形态学专属噪声
    he = z @ W_he + rng.normal(0, 0.9, size=(n_cells, W_he.shape[1]))

    def _panel(W, gain):
        # gain 逐基因不同 → 有的基因强依赖形态(好预测),有的几乎不依赖(难预测)
        lam = np.exp((z @ W) * gain[None, :] * 0.8 + 1.0)
        counts = rng.poisson(np.clip(lam, 1e-3, 200.0))
        return np.log1p(counts)                       # 与 scanpy 常规 log1p 归一一致

    return coords, he, _panel(W_a, gain_a), _panel(W_b, gain_b)


def generate_example_data(outdir=EXAMPLE, n_cells=700, n_prog=10, he_dim=64,
                          n_genes=30, seed=SEED):
    """写出 example_data/ 的合成 CSV。两张切片共享 W(同种组织的两张连续切片)。"""
    os.makedirs(outdir, exist_ok=True)
    rng = np.random.default_rng(seed)
    W_he = rng.normal(0, 1, (n_prog, he_dim))
    W_a = rng.normal(0, 1, (n_prog, n_genes))
    W_b = rng.normal(0, 1, (n_prog, n_genes))
    gain_a = rng.uniform(0.15, 1.4, n_genes)          # 逐基因形态-耦合强度
    gain_b = rng.uniform(0.15, 1.4, n_genes)

    genes_a = [f"PanelA_{i:02d}" for i in range(n_genes)]
    genes_b = [f"PanelB_{i:02d}" for i in range(n_genes)]
    he_cols = [f"HE{i:03d}" for i in range(he_dim)]

    for s in (1, 2):
        cells = [f"S{s}_C{i:04d}" for i in range(n_cells)]
        coords, he, A, B = _make_slice(n_cells, W_he, W_a, W_b, gain_a, gain_b, rng)
        frames = {
            f"slice{s}_coords.csv": pd.DataFrame(coords, index=cells, columns=["x", "y"]),
            f"slice{s}_he.csv": pd.DataFrame(he, index=cells, columns=he_cols),
            f"slice{s}_panelA.csv": pd.DataFrame(A, index=cells, columns=genes_a),
            f"slice{s}_panelB.csv": pd.DataFrame(B, index=cells, columns=genes_b),
        }
        for fname, df in frames.items():
            df.index.name = "cell_id"
            path = os.path.join(outdir, fname)
            with open(path, "w", encoding="utf-8", newline="") as fh:
                fh.write(HEADER)
                df.round(4).to_csv(fh)
    print(f"[578] example_data written to {outdir}")


def _read(name, outdir=EXAMPLE):
    return pd.read_csv(os.path.join(outdir, name), comment="#", index_col=0)


# ---------------------------------------------------------------------------
# 2. 评估指标(沿用上游 utils.Compute_metrics 支持的量:PCC / cosine / CMD)
#    上游定义在 SpatialEx/utils.py:63;PCC 与 CMD 口径与上游一致,
#    cosine 则是本模块自选的逐细胞视角(上游按 axis=0 逐基因算)。
# ---------------------------------------------------------------------------
def per_gene_pcc(true, pred):
    """逐基因 Pearson r。恒定列返回 nan(不当 0 混进均值)。"""
    t = true - true.mean(0, keepdims=True)
    p = pred - pred.mean(0, keepdims=True)
    num = (t * p).sum(0)
    den = np.sqrt((t ** 2).sum(0) * (p ** 2).sum(0))
    out = np.full(true.shape[1], np.nan)
    ok = den > 1e-12
    out[ok] = num[ok] / den[ok]
    return out


def per_cell_cosine(true, pred):
    """逐细胞 cosine similarity(整条表达向量的形状是否对)。

    注意:上游 Compute_metrics(metric='cosine_similarity') 是按 axis=0 逐**基因**算的,
    这里按 axis=1 逐**细胞**算,属本模块自选的补充视角,不要当成上游口径引用。
    """
    num = (true * pred).sum(1)
    den = np.linalg.norm(true, axis=1) * np.linalg.norm(pred, axis=1)
    return np.where(den > 1e-12, num / (den + 1e-12), np.nan)


def cmd(true, pred):
    """Cosine Matrix Distance:比较真值与预测的**基因-基因相关结构**。

    CMD = 1 - tr(R1 R2) / (||R1||_F ||R2||_F),0 = 共表达结构完全一致。
    这一项抓的是逐基因 PCC 抓不到的东西:模型是否重建了基因间的协同关系。
    """
    R1 = np.nan_to_num(np.corrcoef(true, rowvar=False))
    R2 = np.nan_to_num(np.corrcoef(pred, rowvar=False))
    denom = np.linalg.norm(R1) * np.linalg.norm(R2)
    return float(1 - np.trace(R1 @ R2) / denom) if denom > 1e-12 else np.nan


# ---------------------------------------------------------------------------
# 3. 基线:H&E → omics 的岭回归(+ 空间 kNN 平滑),对照全局均值地板
# ---------------------------------------------------------------------------
def spatial_smooth(pred, coords, k=7, alpha=0.5):
    """把预测在空间 kNN 邻域上平滑,近似上游超图的邻域聚合。

    alpha=0 即不平滑;alpha=1 即完全用邻域均值。默认 0.5 = 自身与邻域各半。
    这里只平滑**预测值**,不碰真值 —— 避免把答案泄漏进特征。
    """
    from sklearn.neighbors import NearestNeighbors
    k = int(min(k + 1, coords.shape[0]))
    nn = NearestNeighbors(n_neighbors=k).fit(coords)
    idx = nn.kneighbors(coords, return_distance=False)     # 第 0 列是自身
    neigh_mean = pred[idx].mean(axis=1)
    return (1 - alpha) * pred + alpha * neigh_mean


def translate_one_direction(he_train, y_train, he_test, y_test, coords_test,
                            alpha_ridge=10.0, k=7, alpha_smooth=0.5):
    """在 slice_train 上学 H&E→panel,跨切片应用到 slice_test 上,与真值比。

    ★ 无数据泄漏:训练完全发生在 train 切片,test 切片的表达真值只在评估时读取。
    ★ 跨切片评估(而非切片内 CV)才是上游宣称的能力:把 panel 搬到没测过它的切片上。
    """
    from sklearn.linear_model import Ridge
    from sklearn.preprocessing import StandardScaler

    sc = StandardScaler().fit(he_train)
    model = Ridge(alpha=alpha_ridge, random_state=None)
    model.fit(sc.transform(he_train), y_train)

    preds = {
        # 地板:不看 H&E,一律预测训练切片的基因均值
        "Mean floor": np.tile(y_train.mean(0), (he_test.shape[0], 1)),
        "Ridge (H&E)": model.predict(sc.transform(he_test)),
    }
    preds["Ridge + spatial kNN"] = spatial_smooth(
        preds["Ridge (H&E)"], coords_test, k=k, alpha=alpha_smooth)

    metrics = {}
    for name, P in preds.items():
        g = per_gene_pcc(y_test, P)
        metrics[name] = {
            "median_gene_PCC": float(np.nanmedian(g)),
            "mean_gene_PCC": float(np.nanmean(g)),
            "mean_cell_cosine": float(np.nanmean(per_cell_cosine(y_test, P))),
            "CMD": cmd(y_test, P),
        }
    gene_pcc = pd.DataFrame({n: per_gene_pcc(y_test, P) for n, P in preds.items()})
    return preds, metrics, gene_pcc


# ---------------------------------------------------------------------------
# 4. 出图(框架样式;禁用条形图 → 用 dumbbell / 散点 / 空间图 / heatmap)
# ---------------------------------------------------------------------------
def fig_dumbbell(gene_pcc, genes, outstem):
    """Dumbbell:逐基因 PCC 从"均值地板"到"Ridge"再到"Ridge+空间"的移动。"""
    import matplotlib.pyplot as plt
    order = gene_pcc["Ridge + spatial kNN"].sort_values().index
    y = np.arange(len(order))
    c = pal(3, "npg")
    fig, ax = plt.subplots(figsize=(NATURE_W1 * 1.6, 0.16 * len(order) + 1.4))
    a = gene_pcc.loc[order, "Ridge (H&E)"].values
    b = gene_pcc.loc[order, "Ridge + spatial kNN"].values
    for yi, ai, bi in zip(y, a, b):
        ax.plot([ai, bi], [yi, yi], color="#BBBBBB", lw=1.0, zorder=1)
    ax.scatter(gene_pcc.loc[order, "Mean floor"], y, s=16, color=c[2],
               label="Mean floor", zorder=2)
    ax.scatter(a, y, s=22, color=c[1], label="Ridge (H&E)", zorder=3)
    ax.scatter(b, y, s=22, color=c[0], label="Ridge + spatial kNN", zorder=3)
    ax.axvline(0, color="black", lw=0.8, ls="--")
    ax.set_yticks(y)
    ax.set_yticklabels([genes[i] for i in order], fontsize=6)
    ax.set_xlabel("Per-gene Pearson r (cross-slice held-out)")
    ax.set_title("Histology-anchored panel translation")
    ax.legend(loc="lower right", fontsize=7)
    save_fig(fig, outstem)
    plt.close(fig)


def fig_scatter(y_true, preds, gene_pcc, genes, outstem, n_show=4):
    """散点:预测 vs 真值,取 PCC 分位数上的代表性基因(不只挑最好的)。"""
    import matplotlib.pyplot as plt
    r = gene_pcc["Ridge + spatial kNN"]
    picks = [r.sort_values().index[int(q * (len(r) - 1))] for q in (0.15, 0.5, 0.8, 0.98)][:n_show]
    fig, axes = plt.subplots(1, n_show, figsize=(NATURE_W2, 2.1), constrained_layout=True)
    P = preds["Ridge + spatial kNN"]
    for ax, gi in zip(np.ravel(axes), picks):
        ax.scatter(y_true[:, gi], P[:, gi], s=5, alpha=0.35,
                   color=pal(3, "npg")[0], edgecolors="none", rasterized=True)
        lim = [min(y_true[:, gi].min(), P[:, gi].min()), max(y_true[:, gi].max(), P[:, gi].max())]
        ax.plot(lim, lim, color="black", lw=0.8, ls="--")
        ax.set_title(f"{genes[gi]}\nr = {r[gi]:.2f}", fontsize=7)
        ax.set_xlabel("Measured", fontsize=7)
    np.ravel(axes)[0].set_ylabel("Predicted from H&E", fontsize=7)
    save_fig(fig, outstem)
    plt.close(fig)


def fig_spatial(coords, y_true, preds, gene_pcc, genes, outstem):
    """空间图:同一基因的真值 / Ridge / Ridge+空间 三联,看空间结构是否被还原。"""
    import matplotlib.pyplot as plt
    gi = int(gene_pcc["Ridge + spatial kNN"].idxmax())
    panels = [("Measured", y_true[:, gi])] + \
             [(k, preds[k][:, gi]) for k in ("Ridge (H&E)", "Ridge + spatial kNN")]
    vmin, vmax = np.percentile(np.concatenate([p for _, p in panels]), [2, 98])
    fig, axes = plt.subplots(1, 3, figsize=(NATURE_W2, 2.5), constrained_layout=True)
    for ax, (name, v) in zip(axes, panels):
        sm = ax.scatter(coords[:, 0], coords[:, 1], c=v, s=6, cmap=CMAP_CONT,
                        vmin=vmin, vmax=vmax, edgecolors="none", rasterized=True)
        ax.set_title(name, fontsize=8)
        ax.set_aspect("equal")
        ax.set_xticks([]); ax.set_yticks([])
        for sp in ax.spines.values():
            sp.set_visible(False)
    fig.colorbar(sm, ax=axes, shrink=0.7, label=f"{genes[gi]} (log1p)")
    save_fig(fig, outstem)
    plt.close(fig)


def fig_corr_heatmap(y_true, preds, outstem):
    """Heatmap:真值 vs 预测的基因-基因相关结构(CMD 度量的就是这两块的差)。"""
    import matplotlib.pyplot as plt
    P = preds["Ridge + spatial kNN"]
    R1 = np.nan_to_num(np.corrcoef(y_true, rowvar=False))
    R2 = np.nan_to_num(np.corrcoef(P, rowvar=False))
    o = np.argsort(R1.mean(0))
    fig, axes = plt.subplots(1, 2, figsize=(NATURE_W2 * 0.8, 3.1), constrained_layout=True)
    for ax, M, t in zip(axes, (R1[np.ix_(o, o)], R2[np.ix_(o, o)]),
                        ("Measured gene-gene r", "Predicted gene-gene r")):
        im = ax.imshow(M, cmap=CMAP_DIVERGE, vmin=-1, vmax=1)
        ax.set_title(t, fontsize=8)
        ax.set_xticks([]); ax.set_yticks([])
    fig.colorbar(im, ax=axes, shrink=0.7, label="Pearson r")
    fig.suptitle(f"Co-expression structure  ·  CMD = {cmd(y_true, P):.3f}", fontsize=9)
    save_fig(fig, outstem)
    plt.close(fig)


# ---------------------------------------------------------------------------
# 5. 守卫式上游封装(真实 API,已从上游源码 + 教程核实)
# ---------------------------------------------------------------------------
def run_spatialex(adata1=None, adata2=None):
    """尝试真正的 SpatialEx。未安装 / 无 GPU 则优雅退出并说明原因,绝不静默降级。

    以下调用序列逐个核实自上游源码(KEAML-JLU/SpatialEx @ main),括号内为定义位置:
      · __init__.py:1-4          导出 pp / SpatialEx / SpatialExP / SpatialExP_Big
      · preprocess.py:36,45,67,97,122,140,351   Read_Xenium / Preprocess_adata /
        Read_HE_image / Register_physical_to_pixel / Tiling_HE_patches /
        Extract_HE_patches_representaion / Build_hypergraph_spatial_and_HE
      · SpatialEx.py:39(__init__ :85), 144 train, 194 inference, 238 auto_inference
      · SpatialEx.py:297 SpatialExP(:481 inference_direct, :522 inference_indirect,
        :573 auto_inference);:610 SpatialExP_Big(百万细胞)
      · utils.py:63 Compute_metrics;utils.py:181 create_ImageEncoder(image_encoder 合法值)
    同一序列在官方 Tutorial 1 页面上逐行出现(已实际抓取核对,见 README 链接)。
    """
    try:
        import SpatialEx as se
    except ImportError as e:
        return {"status": "skipped",
                "reason": f"SpatialEx not installed ({e.name}); pip install SpatialEx"}
    try:
        import torch
        gpu = torch.cuda.is_available()
    except ImportError:
        gpu = False
    if not gpu:
        return {"status": "skipped",
                "reason": "no CUDA GPU; SpatialEx trains an HGNN over 1e5-1e6 cells"}

    exported = [n for n in ("SpatialEx", "SpatialExP", "SpatialExP_Big", "pp") if hasattr(se, n)]
    return {
        "status": "ready",
        "exported_api": exported,
        "verified_call_sequence": [
            "adata = se.pp.Read_Xenium(h5_path, obs_path); adata = se.pp.Preprocess_adata(adata)",
            "img, scale = se.pp.Read_HE_image(img_path)",
            "adata = se.pp.Register_physical_to_pixel(adata, transform_mtx, scale=scale)",
            "he_patches, adata = se.pp.Tiling_HE_patches(resolution, adata, img)",
            "adata = se.pp.Extract_HE_patches_representaion(he_patches, adata=adata, "
            "image_encoder='uni', device=device, store_key='he')",
            "graph = se.pp.Build_hypergraph_spatial_and_HE(adata, num_neighbors, "
            "graph_kind='spatial', return_type='crs')",
            "m = se.SpatialEx(adata1, adata2, graph1, graph2, epochs=500, device=device)",
            "m.train(); panelB1, panelA2 = m.auto_inference()",
            "# SpatialEx+ (panel/omics diagonal integration): se.SpatialExP(...) -> "
            "train() -> inference_direct() / inference_indirect() / auto_inference()",
        ],
        "notes": ("需要 adata.obsm['he'](H&E patch embedding)与 adata.obsm['spatial'];"
                  "SpatialEx.__init__ 直接读 obsm['he'](SpatialEx.py:127-128),"
                  "Build_hypergraph_spatial_and_HE 读 obsm['spatial'](preprocess.py:353)。"
                  "image_encoder 默认 'uni'(preprocess.py:140),但 utils.py:205 把 UNI 权重路径"
                  "硬编码成了作者本机目录,换机器必须自行修改。"),
        "docs": "https://spatialex-tutorials.readthedocs.io",
    }


# ---------------------------------------------------------------------------
def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--datadir", default=EXAMPLE, help="输入目录(默认 example_data/)")
    ap.add_argument("--outdir", default=RESULTS, help="输出目录(默认 results/)")
    ap.add_argument("--regen-example-data", action="store_true", help="重新生成合成示例数据")
    ap.add_argument("--ridge-alpha", type=float, default=10.0, help="岭回归正则强度")
    ap.add_argument("--knn", type=int, default=7, help="空间平滑邻居数(对齐上游默认 7)")
    ap.add_argument("--smooth-alpha", type=float, default=0.5, help="空间平滑权重 0-1")
    ap.add_argument("--run-spatialex", action="store_true", help="尝试真正的 SpatialEx(需装包+GPU)")
    a = ap.parse_args()

    np.random.seed(SEED)
    os.makedirs(a.outdir, exist_ok=True)
    os.makedirs(ASSETS, exist_ok=True)
    set_pub_style(base_size=9)

    if a.regen_example_data or not os.path.exists(os.path.join(a.datadir, "slice1_he.csv")):
        print("[578] Step 0 · 生成合成示例数据")
        generate_example_data(a.datadir)

    print("[578] Step 1 · 读入两张切片(坐标 / H&E embedding / panel)")
    he1 = _read("slice1_he.csv", a.datadir); he2 = _read("slice2_he.csv", a.datadir)
    c1 = _read("slice1_coords.csv", a.datadir); c2 = _read("slice2_coords.csv", a.datadir)
    A1 = _read("slice1_panelA.csv", a.datadir); A2 = _read("slice2_panelA.csv", a.datadir)
    B1 = _read("slice1_panelB.csv", a.datadir); B2 = _read("slice2_panelB.csv", a.datadir)
    print(f"       slice1 {he1.shape[0]} cells · HE dim {he1.shape[1]} · "
          f"panelA {A1.shape[1]} genes · panelB {B1.shape[1]} genes")

    # 对角整合设定:slice1 只"测到" panel A,slice2 只"测到" panel B。
    # 另一半是留出的真值,只在评估时读取 —— 训练完全没见过。
    print("[578] Step 2 · panel 对角整合:A(slice1)→slice2,B(slice2)→slice1")
    results, gene_pcc_store, preds_store = {}, {}, {}
    jobs = [
        ("panelA_slice1_to_slice2", he1.values, A1.values, he2.values, A2.values,
         c2.values, list(A1.columns)),
        ("panelB_slice2_to_slice1", he2.values, B2.values, he1.values, B1.values,
         c1.values, list(B1.columns)),
    ]
    for name, hetr, ytr, hete, yte, cte, genes in jobs:
        preds, met, gp = translate_one_direction(
            hetr, ytr, hete, yte, cte,
            alpha_ridge=a.ridge_alpha, k=a.knn, alpha_smooth=a.smooth_alpha)
        results[name] = met
        gene_pcc_store[name] = gp
        preds_store[name] = (preds, yte, cte, genes)
        print(f"       [{name}]")
        for m, v in met.items():
            print(f"         {m:22s} medPCC={v['median_gene_PCC']:+.3f} "
                  f"cellCos={v['mean_cell_cosine']:.3f} CMD={v['CMD']:.3f}")

    print("[578] Step 3 · 写出指标表")
    pd.concat({k: pd.DataFrame(v).T for k, v in results.items()}, names=["direction", "method"]) \
        .to_csv(os.path.join(a.outdir, "578_metrics.csv"))
    for name, gp in gene_pcc_store.items():
        gp.index = preds_store[name][3]
        gp.to_csv(os.path.join(a.outdir, f"578_gene_pcc_{name}.csv"))

    print("[578] Step 4 · 出图(dumbbell / 散点 / 空间图 / heatmap)")
    main_dir = "panelB_slice2_to_slice1"
    preds, y_true, coords, genes = preds_store[main_dir]
    gp = gene_pcc_store[main_dir].reset_index(drop=True)
    for stem, fn in [
        ("578_gene_pcc_dumbbell", lambda p: fig_dumbbell(gp, genes, p)),
        ("578_pred_vs_measured_scatter", lambda p: fig_scatter(y_true, preds, gp, genes, p)),
        ("578_spatial_translation", lambda p: fig_spatial(coords, y_true, preds, gp, genes, p)),
        ("578_coexpression_heatmap", lambda p: fig_corr_heatmap(y_true, preds, p)),
    ]:
        fn(os.path.join(ASSETS, stem))
        print(f"       assets/{stem}.png (+ .pdf)")

    print("[578] Step 5 · SpatialEx 上游路径")
    up = run_spatialex() if a.run_spatialex else {
        "status": "not requested", "hint": "加 --run-spatialex 检测上游可用性(需装包 + GPU)"}
    for k, v in up.items():
        print(f"       {k}: {v}" if not isinstance(v, list) else f"       {k}: {len(v)} items")

    # 依赖版本快照(铁律6:可复现 —— 结果落盘时同时记录环境)
    import platform
    import sklearn
    import matplotlib
    session = {"python": platform.python_version(), "numpy": np.__version__,
               "pandas": pd.__version__, "scikit-learn": sklearn.__version__,
               "matplotlib": matplotlib.__version__, "platform": platform.platform()}

    with open(os.path.join(a.outdir, "578_summary.json"), "w", encoding="utf-8") as fh:
        json.dump({"baseline_metrics": results, "spatialex": up,
                   "params": {"ridge_alpha": a.ridge_alpha, "knn": a.knn,
                              "smooth_alpha": a.smooth_alpha, "seed": SEED},
                   "session_info": session},
                  fh, indent=1, ensure_ascii=False, default=str)
    print(f"[578] done · {os.path.join(a.outdir, '578_summary.json')}")


if __name__ == "__main__":
    main()
