# -*- coding: utf-8 -*-
"""577 · SPIDER — interface-level spatially variable ligand-receptor interactions.

SPIDER (Li S, Wang R, Liu S, Li SC. Nat Commun 2025; doi:10.1038/s41467-025-62988-0,
PMID 40841363) 构建受"细胞互作容量"约束的 cell-cell interaction interface,在
interface 层面刻画并检验 spatially variable interaction (SVI),并用下游 TF/靶基因
提供激活证据。

本模块两条路径:
  1) 本机可跑的 **interface-level 复现 + 朴素基线对照**(默认,只用 numpy/scipy/
     sklearn/scanpy):
       baseline = spot-level LR 共表达打分 → Moran's I(不建 interface,业界常规做法)
       interface = 邻接 spot 对建边 → 定向 L→R 打分 → interface 图上 Moran's I
     两者跑同一套置换检验与 BH 校正,直接看 interface 建模是否捞回 spot 层面丢掉的信号。
  2) 官方 SPIDER 包路径(`--run-spider`),守卫式封装:import 不到就打印真实安装命令
     退出,绝不静默降级。调用序列逐字取自官方 README(见 README.md 的 URL)。

⚠️ 路径 1 是**受 SPIDER 思想启发的最小复现**,不是 SPIDER 算法本身:官方的容量约束
求解(prep 的 itermax 迭代)、多概率模型 SVI 检验(SPARK-X/nnSVG/SOMDE/scGCO)、
TF 下游支持打分均**未复现**。要用官方方法请走路径 2。
"""
from __future__ import annotations

import argparse
import json
import os
import sys

import numpy as np
import pandas as pd

HERE = os.path.dirname(os.path.abspath(__file__))
RESULTS = os.path.join(HERE, "results")
ASSETS = os.path.join(HERE, "assets")
EXAMPLE = os.path.join(HERE, "example_data")

# 统一顶刊出图样式
sys.path.insert(0, os.path.abspath(os.path.join(HERE, "..", "..", "..", "_framework")))
from pubstyle import (  # noqa: E402
    set_pub_style, pal, save_fig, CMAP_CONT, CMAP_DIVERGE, NATURE_W1, NATURE_W2,
)

SEED = 42


# ----------------------------------------------------------------------------- 合成数据
def make_synthetic(outdir: str, n_side: int = 22, seed: int = SEED):
    """生成小型合成空间转录组:两个细胞类型区域 + 一条交界带。

    设计意图(用于验证 interface 建模的必要性):
      - 3 对 "interface-SVI":配体只在 TypeA 表达、受体只在 TypeB 表达 → 单个 spot
        上 L*R 恒低(spot-level 打分看不到),只有跨类型的 interface 才亮;
      - 2 对 "co-expressed":L 与 R 在同一个局部斑块共表达 → 两种打分都该看到;
      - 其余为噪声对。
    """
    rng = np.random.default_rng(seed)
    gx, gy = np.meshgrid(np.arange(n_side), np.arange(n_side))
    xy = np.c_[gx.ravel(), gy.ravel()].astype(float)
    xy += rng.normal(0, 0.12, xy.shape)              # 轻微抖动,避免完美格点退化
    n = xy.shape[0]
    xn = xy[:, 0] / (n_side - 1)

    ctype = np.where(xn < 0.5, "TypeA", "TypeB")

    # 共表达斑块(圆形),与交界带在空间上分开
    blob = ((xy[:, 0] / (n_side - 1) - 0.22) ** 2 +
            (xy[:, 1] / (n_side - 1) - 0.78) ** 2) < 0.03

    lr_pairs, truth = [], {}
    genes, mat = [], []

    def add_gene(name, vec):
        genes.append(name)
        mat.append(np.clip(vec, 0, None))

    for i in range(3):                                # interface-SVI 对
        L, R = f"LIG_IF{i+1}", f"REC_IF{i+1}"
        add_gene(L, np.where(ctype == "TypeA", 3.0, 0.15) + rng.normal(0, .25, n))
        add_gene(R, np.where(ctype == "TypeB", 3.0, 0.15) + rng.normal(0, .25, n))
        lr_pairs.append((L, R)); truth[f"{L}_{R}"] = "interface_SVI"

    for i in range(2):                                # 同 spot 共表达对
        L, R = f"LIG_CO{i+1}", f"REC_CO{i+1}"
        v = np.where(blob, 3.0, 0.2)
        add_gene(L, v + rng.normal(0, .25, n))
        add_gene(R, v + rng.normal(0, .25, n))
        lr_pairs.append((L, R)); truth[f"{L}_{R}"] = "coexpressed_SVI"

    for i in range(7):                                # 噪声对(空间无结构)
        L, R = f"LIG_NS{i+1}", f"REC_NS{i+1}"
        add_gene(L, rng.gamma(2, .6, n))
        add_gene(R, rng.gamma(2, .6, n))
        # 标签用 no_signal 而非 "null":pandas 会把字符串 "null" 读成 NaN
        lr_pairs.append((L, R)); truth[f"{L}_{R}"] = "no_signal"

    expr = pd.DataFrame(np.array(mat).T, columns=genes)
    meta = pd.DataFrame({"spot": [f"S{i:04d}" for i in range(n)],
                         "x": xy[:, 0], "y": xy[:, 1], "cell_type": ctype})
    lr = pd.DataFrame(lr_pairs, columns=["ligand", "receptor"])

    os.makedirs(outdir, exist_ok=True)
    hdr = "# synthetic, for demo only -- generated by 577_spider_spatial_ccc.py\n"
    for name, df in (("expression.csv", pd.concat([meta[["spot"]], expr], axis=1)),
                     ("spot_meta.csv", meta),
                     ("lr_pairs.csv", lr)):
        p = os.path.join(outdir, name)
        with open(p, "w", newline="") as fh:
            fh.write(hdr)
            df.to_csv(fh, index=False)
    with open(os.path.join(outdir, "ground_truth.json"), "w") as fh:
        json.dump(truth, fh, indent=1)
    return meta, expr, lr, truth


def load_data(datadir: str):
    def rd(f):
        return pd.read_csv(os.path.join(datadir, f), comment="#")
    meta = rd("spot_meta.csv")
    expr = rd("expression.csv").set_index("spot")
    lr = rd("lr_pairs.csv")
    tp = os.path.join(datadir, "ground_truth.json")
    if os.path.exists(tp):
        with open(tp) as fh:
            truth = json.load(fh)
    else:
        truth = {}
    return meta, expr, lr, truth


# ----------------------------------------------------------------------------- 空间统计
def knn_weights(coords: np.ndarray, k: int = 6):
    """行标准化 kNN 空间权重矩阵(稀疏,列表形式)。"""
    from sklearn.neighbors import NearestNeighbors
    k = min(k, len(coords) - 1)
    nn = NearestNeighbors(n_neighbors=k + 1).fit(coords)
    idx = nn.kneighbors(coords, return_distance=False)[:, 1:]
    return idx


def morans_I(x: np.ndarray, nbr_idx: np.ndarray) -> float:
    """Moran's I,行标准化权重(每个邻居权重 1/k),等价于 z 与邻居均值 z 的相关。"""
    z = x - x.mean()
    denom = (z ** 2).sum()
    if denom <= 0:
        return 0.0
    lag = z[nbr_idx].mean(axis=1)
    return float((z * lag).sum() / denom)


def morans_I_mat(X: np.ndarray, nbr_idx: np.ndarray) -> np.ndarray:
    """对 X 的每一列并行算 Moran's I(X: n_obs × n_cols)。"""
    Z = X - X.mean(axis=0, keepdims=True)
    denom = (Z ** 2).sum(axis=0)
    lag = Z[nbr_idx, :].mean(axis=1)          # (n_obs, n_cols)
    num = (Z * lag).sum(axis=0)
    return np.where(denom > 0, num / np.where(denom > 0, denom, 1), 0.0)


def emp_p(obs: float, null: np.ndarray) -> float:
    """经验单侧 p(右尾),含 +1 校正,下界 1/(n_perm+1)。"""
    return float((1 + (null >= obs).sum()) / (len(null) + 1))


def bh_fdr(p: np.ndarray) -> np.ndarray:
    p = np.asarray(p, float)
    o = np.argsort(p)
    q = p[o] * len(p) / (np.arange(len(p)) + 1)
    q = np.minimum.accumulate(q[::-1])[::-1]
    out = np.empty_like(q)
    out[o] = np.clip(q, 0, 1)
    return out


# ----------------------------------------------------------------------------- interface 构建
def build_interfaces(meta: pd.DataFrame, max_degree: int = 6, dist_quantile: float = 0.9):
    """由 Delaunay 三角剖分取邻接 spot 对建 interface,并做容量约束。

    ⚠️ 简化说明:SPIDER 官方用迭代优化(prep 的 itermax)来施加"细胞互作容量"约束;
    这里只做一个可解释的近似——① 丢掉过长的边(距离 > dist_quantile 分位数),
    ② 每个 spot 至多保留 max_degree 条最短的边。**不等价于官方实现**。
    """
    from scipy.spatial import Delaunay
    coords = meta[["x", "y"]].to_numpy()
    tri = Delaunay(coords)
    edges = set()
    for s in tri.simplices:
        for a, b in ((0, 1), (1, 2), (0, 2)):
            i, j = sorted((int(s[a]), int(s[b])))
            edges.add((i, j))
    e = np.array(sorted(edges))
    d = np.linalg.norm(coords[e[:, 0]] - coords[e[:, 1]], axis=1)
    keep = d <= np.quantile(d, dist_quantile)
    e, d = e[keep], d[keep]

    # 容量约束:按边长升序贪心,超过 max_degree 的边丢弃
    order = np.argsort(d)
    deg = np.zeros(len(coords), int)
    sel = []
    for k in order:
        i, j = e[k]
        if deg[i] < max_degree and deg[j] < max_degree:
            deg[i] += 1; deg[j] += 1; sel.append(k)
    sel = np.sort(np.array(sel))
    e, d = e[sel], d[sel]

    mid = (coords[e[:, 0]] + coords[e[:, 1]]) / 2
    ct = meta["cell_type"].to_numpy()
    label = np.array(["--".join(sorted((ct[i], ct[j]))) for i, j in e])
    idf = pd.DataFrame({"i": e[:, 0], "j": e[:, 1], "x": mid[:, 0], "y": mid[:, 1],
                        "length": d, "interface_type": label})
    return idf


# ----------------------------------------------------------------------------- 打分 + 检验
def score_and_test(meta, expr, lr, idf, n_perm=999, k_spot=6, k_iface=6, seed=SEED):
    """两条打分路线各自做 Moran's I 置换检验。

    ★ 零假设的构造方式很关键:置换必须打在 **spot 标签** 上,而不是打在算好的
    interface 打分上。相邻的两条 interface 共用同一个 spot,打分天然相关,直接置换
    interface 值的零分布会低估这份结构性自相关 → 每个噪声 LR 对都会假阳性。
    改成打散 spot 再重算 interface 打分,零分布就保留了共用 spot 的依赖结构。
    两条路线共用同一批置换,配对可比。
    """
    rng = np.random.default_rng(seed)
    X = expr.to_numpy()
    gi = {g: c for c, g in enumerate(expr.columns)}
    n = len(meta)
    spot_nbr = knn_weights(meta[["x", "y"]].to_numpy(), k_spot)
    if_nbr = knn_weights(idf[["x", "y"]].to_numpy(), k_iface)
    i_idx, j_idx = idf["i"].to_numpy(), idf["j"].to_numpy()

    # 预生成 spot 置换(所有 LR 对共用 → 检验之间配对,且省算力)
    perms = np.stack([rng.permutation(n) for _ in range(n_perm)], axis=1)   # n × n_perm

    def iface_score(l, rc):
        """双向 L->R 取均值(边无向,两端都可能是配体侧);支持列向量批量。"""
        l, rc = np.clip(l, 0, None), np.clip(rc, 0, None)
        return (np.sqrt(l[i_idx] * rc[j_idx]) + np.sqrt(l[j_idx] * rc[i_idx])) / 2

    rows, if_scores = [], {}
    for _, r in lr.iterrows():
        L, R = r["ligand"], r["receptor"]
        if L not in gi or R not in gi:
            continue
        l, rc = X[:, gi[L]], X[:, gi[R]]
        key = f"{L}_{R}"
        lp, rp = l[perms], rc[perms]                       # n × n_perm 的置换表达

        # baseline:spot-level 共表达打分(几何均值),常规的"不建 interface"做法
        s_spot = np.sqrt(np.clip(l, 0, None) * np.clip(rc, 0, None))
        S_spot = np.sqrt(np.clip(lp, 0, None) * np.clip(rp, 0, None))
        I_s = morans_I(s_spot, spot_nbr)
        p_s = emp_p(I_s, morans_I_mat(S_spot, spot_nbr))

        # interface-level:同一批 spot 置换下重算 interface 打分
        s_if = iface_score(l, rc)
        S_if = iface_score(lp, rp)
        I_i = morans_I(s_if, if_nbr)
        p_i = emp_p(I_i, morans_I_mat(S_if, if_nbr))

        if_scores[key] = s_if
        rows.append(dict(lr_pair=key, ligand=L, receptor=R,
                         spot_moranI=I_s, spot_p=p_s,
                         iface_moranI=I_i, iface_p=p_i,
                         iface_mean_score=float(s_if.mean())))
    res = pd.DataFrame(rows)
    res["spot_fdr"] = bh_fdr(res["spot_p"].to_numpy())
    res["iface_fdr"] = bh_fdr(res["iface_p"].to_numpy())
    res["delta_moranI"] = res["iface_moranI"] - res["spot_moranI"]
    return res.sort_values("iface_moranI", ascending=False).reset_index(drop=True), if_scores


# ----------------------------------------------------------------------------- 出图(无条形图)
def figures(meta, idf, res, if_scores, outdir):
    import matplotlib.pyplot as plt
    set_pub_style(base_size=9)
    os.makedirs(ASSETS, exist_ok=True)
    C = pal(6, "npg")

    # fig1 · interface 图:spot 散点 + 边着色为 interface 打分
    # 优先挑"只有 interface 层面显著、spot 层面漏掉"的对 —— 这才是建 interface 的意义;
    # 没有这种对时退回 interface Moran's I 最高的对。
    gain = res[(res["iface_fdr"] < .05) & (res["spot_fdr"] >= .05)]
    top = (gain.sort_values("iface_moranI", ascending=False).iloc[0]["lr_pair"]
           if len(gain) else res.iloc[0]["lr_pair"])
    v = if_scores[top]
    fig, ax = plt.subplots(figsize=(NATURE_W1 + 0.9, NATURE_W1 + 0.5))
    from matplotlib.collections import LineCollection
    xy = meta[["x", "y"]].to_numpy()
    seg = np.stack([xy[idf["i"].to_numpy()], xy[idf["j"].to_numpy()]], axis=1)
    o = np.argsort(v)
    lc = LineCollection(seg[o], array=v[o], cmap=CMAP_CONT, linewidths=1.6)
    ax.add_collection(lc)
    for c, col in zip(sorted(meta["cell_type"].unique()), C):
        m = meta["cell_type"] == c
        ax.scatter(meta.loc[m, "x"], meta.loc[m, "y"], s=7, color=col,
                   edgecolor="white", linewidth=.2, label=c, zorder=3)
    ax.set(xlabel="Spatial x", ylabel="Spatial y",
           title=f"Interface graph, score of {top}")
    ax.set_aspect("equal"); ax.autoscale_view()
    ax.legend(loc="upper left", bbox_to_anchor=(0, -0.16), ncol=2, markerscale=1.6)
    fig.colorbar(lc, ax=ax, shrink=.7, label="Interface LR score")
    save_fig(fig, os.path.join(ASSETS, "fig1_interface_graph")); plt.close(fig)

    # fig2 · dumbbell:同一 LR 对在 spot-level 与 interface-level 的 Moran's I
    d = res.sort_values("iface_moranI")
    y = np.arange(len(d))
    fig, ax = plt.subplots(figsize=(NATURE_W1 + 1.5, 0.24 * len(d) + 1.4))
    ax.hlines(y, d["spot_moranI"], d["iface_moranI"], color="#BBBBBB", lw=1.4, zorder=1)
    # 实心 = 该层面 FDR<0.05,空心 = 不显著。必须编码显著性:interface 打分因相邻边共用
    # spot 而存在结构性自相关下限,光看 Moran's I 高低会把噪声对误读成信号。
    for col, key, fdr, lab in ((C[3], "spot_moranI", "spot_fdr", "Spot-level (baseline)"),
                               (C[0], "iface_moranI", "iface_fdr", "Interface-level")):
        sig = (d[fdr] < .05).to_numpy()
        ax.scatter(d[key][sig], y[sig], s=36, color=col, label=lab, zorder=2)
        ax.scatter(d[key][~sig], y[~sig], s=36, facecolor="white", edgecolor=col,
                   linewidth=1.1, zorder=2)
    ax.axvline(0, color="black", lw=.7, ls=":")
    ax.set_yticks(y); ax.set_yticklabels(d["lr_pair"], fontsize=7)
    ax.set(xlabel="Moran's I", title="Interface vs spot-level spatial autocorrelation")
    ax.legend(loc="lower right", title="Filled = FDR < 0.05")
    save_fig(fig, os.path.join(ASSETS, "fig2_moran_dumbbell")); plt.close(fig)

    # fig3 · lollipop:interface-level SVI 显著性排序
    d = res.sort_values("iface_fdr", ascending=False)
    y = np.arange(len(d))
    val = -np.log10(np.clip(d["iface_fdr"], 1e-6, None))
    fig, ax = plt.subplots(figsize=(NATURE_W1 + 1.3, 0.24 * len(d) + 1.4))
    ax.hlines(y, 0, val, color="#CCCCCC", lw=1.3)
    sc = ax.scatter(val, y, s=38 + 90 * d["iface_mean_score"] / d["iface_mean_score"].max(),
                    c=d["iface_moranI"], cmap=CMAP_CONT, zorder=3,
                    edgecolor="black", linewidth=.3)
    ax.axvline(-np.log10(0.05), color=C[0], lw=.9, ls="--")
    ax.set_yticks(y); ax.set_yticklabels(d["lr_pair"], fontsize=7)
    ax.set(xlabel=r"$-\log_{10}$ FDR (interface-level)",
           title="Spatially variable interactions")
    fig.colorbar(sc, ax=ax, shrink=.6, label="Moran's I")
    save_fig(fig, os.path.join(ASSETS, "fig3_svi_lollipop")); plt.close(fig)

    # fig4 · heatmap:LR 对 × interface 类型的平均打分(z-score)
    keys = list(res["lr_pair"])
    types = sorted(idf["interface_type"].unique())
    M = np.array([[if_scores[k][(idf["interface_type"] == t).to_numpy()].mean()
                   for t in types] for k in keys])
    Z = (M - M.mean(1, keepdims=True)) / (M.std(1, keepdims=True) + 1e-9)
    fig, ax = plt.subplots(figsize=(0.9 * len(types) + 2.4, 0.26 * len(keys) + 1.5))
    im = ax.imshow(Z, cmap=CMAP_DIVERGE, aspect="auto",
                   vmin=-np.abs(Z).max(), vmax=np.abs(Z).max())
    ax.set_xticks(range(len(types))); ax.set_xticklabels(types, rotation=30, ha="right", fontsize=7)
    ax.set_yticks(range(len(keys))); ax.set_yticklabels(keys, fontsize=7)
    ax.set(title="Interface score by cell-type pair")
    fig.colorbar(im, ax=ax, shrink=.7, label="Row z-score")
    save_fig(fig, os.path.join(ASSETS, "fig4_interface_type_heatmap")); plt.close(fig)

    # fig5 · 散点:interface 打分的空间分布(top SVI vs 一个 null 对)
    null_key = res.sort_values("iface_moranI").iloc[0]["lr_pair"]
    fig, axes = plt.subplots(1, 2, figsize=(NATURE_W2, NATURE_W1 - 0.2))
    for ax, key in zip(axes, [top, null_key]):
        s = if_scores[key]
        sc = ax.scatter(idf["x"], idf["y"], c=s, s=6, cmap=CMAP_CONT)
        ax.set(xlabel="Spatial x", ylabel="Spatial y", title=key)
        ax.set_aspect("equal")
        fig.colorbar(sc, ax=ax, shrink=.75, label="Interface score")
    save_fig(fig, os.path.join(ASSETS, "fig5_interface_score_maps")); plt.close(fig)


# ----------------------------------------------------------------------------- 官方 SPIDER(守卫)
def run_official_spider(adata_path, out_f, r_path, cluster_key=None, is_human=None, is_sc=None):
    """守卫式封装:调用序列取自官方 README,并已逐个比对官方源码签名。

    核对来源(2026-07-20 抓取,非仅凭 README):
      spider/__init__.py            : `from .SPIDER import SPIDER`  → `import spider; spider.SPIDER()`
      spider/SPIDER.py  SPIDER.prep(adata_input, cluster_key='type', is_human=True, cutoff=None,
                                    imputation=False, itermax=1000, lr_raw=None, pathway_raw=None,
                                    is_sc=False, normalize_total=False) -> idata
      spider/SPIDER.py  SPIDER.find_svi(idata, out_f, R_path, abstract=True, overwrite=False,
                                    n_neighbors=5, alpha=0.3, threshold=0.01, ...,
                                    svi_number=10, n_jobs=10) -> (idata, meta_idata)
      spider/svi.py     tf_corr(idata, adata, is_human, out_f, threshold=0.3, ...)
      spider/svi.py     combine_SVI(idata, threshold, svi_number=10) -> (svi_df, svi_df_strict)

    ★ out_f 必须以路径分隔符结尾:官方全程用 f-string 直接拼接,不用 os.path.join。
      实测计数(2026-07-21 对本地克隆源码):spider/svi.py 内 f'{out_f}...' 13 处
      (如 svi.py:118 f'{out_f}sparse_tf_corr.npz'),另 f'{work_dir}...' 35 处
      —— find_svi(SPIDER.py:180)把 out_f 按位置传给 svi.find_svi(svi.py:386)的
      work_dir,再传给 svi_moran/svi_nnSVG 等;SPIDER.py 内另有 f'{out_f}pattern.csv'
      等 13 处(SPIDER.py:170-188),util.py 1 处 —— 全仓 f'{out_f}' 合计 27 处。
      全仓 os.path.join 仅 5 处,全在 vendored
      SpatialDE2/io.py(spaceranger 读图),SPIDER 核心模块 0 处。
      不带分隔符会把文件写到上级目录、并让 find_svi 的 `mkdir(out_f)`
      (SPIDER.py:155,159,非递归)建出错目录。此处统一补上。

    未安装则返回真实安装命令,不做任何静默替代。
    """
    try:
        import spider  # noqa: F401
    except ImportError:
        return {"status": "skipped",
                "reason": "package `spider` (PyPI: spider-st) not installed",
                "install": ["conda create -n spider python=3.8",
                            "conda install -c conda-forge somoclu fa2",
                            "pip install Cython",
                            "SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL=TRUE pip install sklearn",
                            "pip install scgco",
                            "pip install spider-st"],
                "no_install_option": "CodeOcean capsule https://codeocean.com/capsule/1194038/tree/v1"}
    if adata_path is None:
        return {"status": "skipped",
                "reason": "official path needs --adata (an .h5ad). cluster_key/is_human/is_sc "
                          "由 --cluster-key/--is-human/--is-sc 指定;未指定则回落到 adata.uns "
                          "同名键(官方 README 的写法),再没有就用官方源码默认值 "
                          "cluster_key='type', is_human=True, is_sc=False"}
    import anndata
    adata = anndata.read_h5ad(adata_path)

    # README 的 Quick Start 直接读 adata.uns['cluster_key'] 等键,但这三个键并非 h5ad 标准内容,
    # 缺失即 KeyError。故:命令行 > adata.uns > 官方源码签名里的默认值。
    ck = cluster_key if cluster_key else adata.uns.get("cluster_key", "type")
    hum = is_human if is_human is not None else bool(adata.uns.get("is_human", True))
    sc_ = is_sc if is_sc is not None else bool(adata.uns.get("is_sc", False))

    out_f = out_f.rstrip("/\\") + os.sep          # 官方按 f'{out_f}xxx.csv' 拼接,必须带分隔符
    os.makedirs(out_f, exist_ok=True)             # 官方 find_svi 用的是非递归 mkdir

    op = spider.SPIDER()
    idata = op.prep(adata, cluster_key=ck, is_human=hum, is_sc=sc_,
                    itermax=1000, imputation=True, normalize_total=True)
    op.svi.tf_corr(idata, adata, hum, out_f, threshold=0.3)
    idata, meta_idata = op.find_svi(idata, out_f, r_path, alpha=0.3, overwrite=True,
                                    n_jobs=1, svi_number=0)
    svi_df, svi_df_strict = op.svi.combine_SVI(idata, threshold=0.01)
    svi_df.to_csv(os.path.join(out_f, "spider_svi.csv"))
    svi_df_strict.to_csv(os.path.join(out_f, "spider_svi_strict.csv"))
    return {"status": "ok", "out_f": out_f,
            "n_svi": int(len(svi_df)), "n_svi_strict": int(len(svi_df_strict))}


# ----------------------------------------------------------------------------- main
def main():
    ap = argparse.ArgumentParser(description="577 SPIDER-style interface-level SVI + baseline")
    ap.add_argument("--datadir", default=EXAMPLE, help="含 expression.csv/spot_meta.csv/lr_pairs.csv")
    ap.add_argument("--outdir", default=RESULTS)
    ap.add_argument("--max-degree", type=int, default=6, help="每个 spot 最多保留的 interface 数")
    ap.add_argument("--n-perm", type=int, default=999)
    ap.add_argument("--k-neighbors", type=int, default=6)
    ap.add_argument("--seed", type=int, default=SEED)
    ap.add_argument("--run-spider", action="store_true", help="走官方 spider-st 包(需安装)")
    ap.add_argument("--adata", default=None, help="官方路径的 .h5ad 输入")
    ap.add_argument("--r-path", default="", help="官方 find_svi 的 R_path")
    ap.add_argument("--cluster-key", default=None,
                    help="官方 prep 的 cluster_key(缺省读 adata.uns,再缺省用官方默认 'type')")
    ap.add_argument("--is-human", dest="is_human", action="store_true", default=None)
    ap.add_argument("--is-mouse", dest="is_human", action="store_false",
                    help="官方 prep 的 is_human=False")
    ap.add_argument("--is-sc", dest="is_sc", action="store_true", default=None,
                    help="官方 prep 的 is_sc=True(单细胞分辨率数据)")
    a = ap.parse_args()
    os.makedirs(a.outdir, exist_ok=True)

    if not os.path.exists(os.path.join(a.datadir, "expression.csv")):
        print("[577] Step 0 · 生成合成示例数据")
        make_synthetic(a.datadir, seed=a.seed)
    meta, expr, lr, truth = load_data(a.datadir)
    print(f"[577] Step 1 · 载入 {len(meta)} spots × {expr.shape[1]} genes, {len(lr)} LR pairs")

    idf = build_interfaces(meta, max_degree=a.max_degree)
    print(f"[577] Step 2 · 构建 {len(idf)} 条 interface(容量约束 max_degree={a.max_degree})")

    res, if_scores = score_and_test(meta, expr, lr, idf, n_perm=a.n_perm,
                                    k_spot=a.k_neighbors, k_iface=a.k_neighbors, seed=a.seed)
    print(f"[577] Step 3 · Moran's I 置换检验({a.n_perm} perms)+ BH 校正")

    if truth:
        res["truth"] = res["lr_pair"].map(truth).fillna("unknown")
        pos = res["truth"].isin(["interface_SVI", "coexpressed_SVI"])
        rec = {"interface_level_recall": float(((res["iface_fdr"] < .05) & pos).sum() / pos.sum()),
               "spot_level_recall": float(((res["spot_fdr"] < .05) & pos).sum() / pos.sum()),
               "interface_level_FP": int(((res["iface_fdr"] < .05) & ~pos).sum()),
               "spot_level_FP": int(((res["spot_fdr"] < .05) & ~pos).sum())}
        print("[577] Step 4 · 对照(合成 ground truth):")
        for k, v in rec.items():
            print(f"        {k}: {v}")
    else:
        rec = {"note": "no ground_truth.json in datadir; recall not computed"}

    idf.to_csv(os.path.join(a.outdir, "interfaces.csv"), index=False)
    res.to_csv(os.path.join(a.outdir, "svi_results.csv"), index=False)
    print("[577] Step 5 · 出图")
    figures(meta, idf, res, if_scores, a.outdir)

    summary = {"n_spots": int(len(meta)), "n_interfaces": int(len(idf)),
               "n_lr_pairs": int(len(res)), "seed": a.seed, "n_perm": a.n_perm,
               "benchmark_vs_synthetic_truth": rec,
               "top_interface_SVI": res.head(5)[["lr_pair", "iface_moranI", "iface_fdr"]]
                                       .to_dict("records")}
    if a.run_spider:
        print("[577] Step 6 · 官方 SPIDER 路径")
        summary["official_spider"] = run_official_spider(
            a.adata, a.outdir, a.r_path,
            cluster_key=a.cluster_key, is_human=a.is_human, is_sc=a.is_sc)
        print(f"        {summary['official_spider']}")
    else:
        summary["official_spider"] = {"status": "not requested (--run-spider)"}

    with open(os.path.join(a.outdir, "577_summary.json"), "w") as fh:
        json.dump(summary, fh, indent=1, default=str)

    # 依赖版本快照(铁律6:可复现)
    import platform
    import scipy, sklearn, matplotlib
    with open(os.path.join(a.outdir, "versions.txt"), "w") as fh:
        fh.write(f"python\t{platform.python_version()}\nplatform\t{platform.platform()}\n")
        for m in (np, pd, scipy, sklearn, matplotlib):
            fh.write(f"{m.__name__}\t{getattr(m, '__version__', '?')}\n")
        try:
            import spider
            fh.write(f"spider\t{getattr(spider, '__version__', 'installed')}\n")
        except ImportError:
            fh.write("spider\tNOT INSTALLED (official path unavailable)\n")
    print(f"[577] done → {a.outdir}")


if __name__ == "__main__":
    main()
