# -*- coding: utf-8 -*-
"""生成 581 模块的合成示例数据(只需跑一次,产物已提交到 example_data/)。

合成逻辑:细胞散布在 2D 组织切片上,潜在分化时间 t 与空间位置强相关(空间梯度);
基因沿 t 单调上升或下降,未剪接(unspliced)超前于剪接(spliced) —— 这正是 RNA
velocity 读取的信号。再往 spliced/unspliced 里加空间不相关的计数噪声,使得
「空间邻域平滑」有可能去噪 —— 这样空间基线才是可被证伪的,而不是自动获胜。
"""
from pathlib import Path
import numpy as np
import pandas as pd

HERE = Path(__file__).parent
OUT = HERE / "example_data"
OUT.mkdir(exist_ok=True)

SEED = 2026
N_CELLS, N_GENES = 400, 60
rng = np.random.default_rng(SEED)

# ---- 空间坐标:20x20 网格 + 抖动 ----
gx, gy = np.meshgrid(np.arange(20), np.arange(20))
xy = np.c_[gx.ravel(), gy.ravel()].astype(float)
xy = xy[rng.permutation(len(xy))[:N_CELLS]]
xy += rng.normal(0, 0.15, xy.shape)

# ---- 潜在时间 = 空间梯度(对角方向)+ 少量非空间噪声 ----
grad = (xy[:, 0] + xy[:, 1])
t = (grad - grad.min()) / (grad.max() - grad.min())
t = np.clip(t + rng.normal(0, 0.05, N_CELLS), 0, 1)

# ---- 基因动力学:base 水平 + 方向(±1) ----
base = rng.uniform(0.8, 4.0, N_GENES)
direction = rng.choice([1, -1], N_GENES)
prof = base[None, :] * (1.0 + 0.8 * direction[None, :] * t[:, None])
prof = np.clip(prof, 0.05, None)

# unspliced 超前 spliced(沿 t 的导数方向),这是 velocity 的来源
unspliced_rate = np.clip(prof * (1.0 + 0.45 * direction[None, :]), 0.05, None)

spliced = rng.poisson(prof * 6.0).astype(int)
unspliced = rng.poisson(unspliced_rate * 6.0).astype(int)

cells = [f"C{i:04d}" for i in range(N_CELLS)]
genes = [f"G{i:03d}" for i in range(N_GENES)]

# 简单空间分区当作 cluster 标签(仅用于配色/分组,不参与速度估计)
cluster = pd.cut(t, bins=[-0.01, 0.33, 0.66, 1.01],
                 labels=["early", "mid", "late"]).astype(str)

meta = pd.DataFrame({"cell": cells, "x": xy[:, 0].round(3), "y": xy[:, 1].round(3),
                     "true_time": t.round(4), "cluster": cluster})
truth = pd.DataFrame({"gene": genes, "true_direction": direction})

HDR = "# synthetic, for demo only -- generated by _make_example_data.py (seed=2026)\n"


def _write(df, name, index=False):
    p = OUT / name
    with open(p, "w", newline="") as fh:
        fh.write(HDR)
        df.to_csv(fh, index=index)
    print("wrote", p)


_write(pd.DataFrame(spliced, index=cells, columns=genes), "spliced.csv", index=True)
_write(pd.DataFrame(unspliced, index=cells, columns=genes), "unspliced.csv", index=True)
_write(meta, "spatial_meta.csv")
_write(truth, "gene_truth.csv")
